// Generated by ReScript, PLEASE EDIT WITH CARE

const Js_ = {};

function fromJs(js) {
  return {
    closed: js.closed,
    unsubscribe(param) {
      js.unsubscribe();
    }
  };
}

const Subscription = {
  Js_,
  fromJs
};

const Js_$1 = {};

const Observer = {
  Js_: Js_$1
};

const Js_$2 = {};

const Observable = {
  Js_: Js_$2
};

exports.Subscription = Subscription;
exports.Observer = Observer;
exports.Observable = Observable;
/* No side effect */
